version: '3.1'

services:
  rabbit-mq-one:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15671:15672
      - 15691:15692
      - 5671:5672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

  rabbit-mq-two:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 15692:15692
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root